# This file was generated by the release pipeline. DO NOT EDIT.
cask "sendit" do
  name "sendit"
  desc "Traffic generation tool for HTTP, DNS, WebSocket, and headless-browser targets."
  homepage "https://github.com/lewta/sendit"
  version "0.13.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sendit"
  bash_completion "completions/sendit.bash"
  zsh_completion "completions/sendit.zsh"
  fish_completion "completions/sendit.fish"

  on_macos do
    on_intel do
      url "https://github.com/lewta/sendit/releases/download/v#{version}/sendit_#{version}_darwin_amd64.tar.gz"
      sha256 "e4d705a41ccf5f7bea74cfa13c5eb636ea061711d42daad18e5fcd12613da306"
    end
    on_arm do
      url "https://github.com/lewta/sendit/releases/download/v#{version}/sendit_#{version}_darwin_arm64.tar.gz"
      sha256 "6a534d9810e331e2cb782e9bbe8fe5c1ac99a18c8a6d8bb4fc3ea0fd10b50b36"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lewta/sendit/releases/download/v#{version}/sendit_#{version}_linux_amd64.tar.gz"
      sha256 "d8e09e9947ece28eca6fa0034016532c1fd746a78448d1b440afd34b64cb187d"
    end
    on_arm do
      url "https://github.com/lewta/sendit/releases/download/v#{version}/sendit_#{version}_linux_arm64.tar.gz"
      sha256 "d454fc0dee44c4ab1664b3ea0e9089051634adfb267c5c94df1ac8714cba68e5"
    end
  end

  # No zap stanza required
end
