# This file was generated by GoReleaser. DO NOT EDIT.
cask "sendit" do
  name "sendit"
  desc "Traffic generation tool for HTTP, DNS, WebSocket, and headless-browser targets."
  homepage "https://github.com/lewta/sendit"
  version "0.10.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sendit"
  bash_completion "completions/sendit.bash"
  zsh_completion "completions/sendit.zsh"
  fish_completion "completions/sendit.fish"

  on_macos do
    on_intel do
      url "https://github.com/lewta/sendit/releases/download/v#{version}/sendit_#{version}_darwin_amd64.tar.gz"
      sha256 "894bdee670d53761c7a7a5f82db35b963d441f4989d9bac9d690ff56599da2dc"
    end
    on_arm do
      url "https://github.com/lewta/sendit/releases/download/v#{version}/sendit_#{version}_darwin_arm64.tar.gz"
      sha256 "18ed79cc8c05ffe6c45763bc8fc09a053acdf8006bd5ab36de4e7f065e170295"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lewta/sendit/releases/download/v#{version}/sendit_#{version}_linux_amd64.tar.gz"
      sha256 "759c068d419ba86872578c824a54fbc5041151dd9b711d84d044df92ba6ab22e"
    end
    on_arm do
      url "https://github.com/lewta/sendit/releases/download/v#{version}/sendit_#{version}_linux_arm64.tar.gz"
      sha256 "89a5307c2f69452f01c35559b140d7eb84c2797a68a2f6d6ca0140a08368aa34"
    end
  end

  # No zap stanza required
end
