# This file was generated by the release pipeline. DO NOT EDIT.
cask "sendit" do
  name "sendit"
  desc "Traffic generation tool for HTTP, DNS, WebSocket, and headless-browser targets."
  homepage "https://github.com/lewta/sendit"
  version "0.10.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sendit"
  bash_completion "completions/sendit.bash"
  zsh_completion "completions/sendit.zsh"
  fish_completion "completions/sendit.fish"

  on_macos do
    on_intel do
      url "https://github.com/lewta/sendit/releases/download/v#{version}/sendit_#{version}_darwin_amd64.tar.gz"
      sha256 "a1e6600b4f6d84ca177f6d29756b077b2ca868a54f61d3c78af75a944fa53f36"
    end
    on_arm do
      url "https://github.com/lewta/sendit/releases/download/v#{version}/sendit_#{version}_darwin_arm64.tar.gz"
      sha256 "78da689274c8b14a84bf77df9123f20a99f20985125f033dfc8dea759a6dbb66"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lewta/sendit/releases/download/v#{version}/sendit_#{version}_linux_amd64.tar.gz"
      sha256 "a4596a7445fcaade5caae656ebfe7effd94a666b864240534fa24c10e4f33102"
    end
    on_arm do
      url "https://github.com/lewta/sendit/releases/download/v#{version}/sendit_#{version}_linux_arm64.tar.gz"
      sha256 "5a8d937aa83578479ca5ba13b3edd9aebc113c539a95efba7c7f7d5e9e481286"
    end
  end

  # No zap stanza required
end
